version: 2.1

orbs:
  unity: game-ci/unity@1.4.0

workflows:
  build-unity-project:
    jobs:
      - unity/build:
          name: 'build-Windows64-il2cpp'
          step-name: 'Build StandaloneWindows64 il2cpp'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/windows-2022'
            # resource_class: 'xlarge'
            editor_version: '2022.3.1f1'
            target_platform: 'windows-il2cpp'
          project-path: 'WorldWarRoyale/TPS'
          build-target: StandaloneWindows64
          compress: true
          context: all